name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install jsverify
      - name: Install jsverify
        run: npm install jsverify
        working-directory: ./frontend  # Adjust this if needed

      # Run tests for WildCardCocktailSort.js (code.test.js)
      - name: Run Tests for WildCardCocktailSort.js (code.test.js)
        run: node code.test.js
        working-directory: ./frontend  # Adjust this if needed

      # Run tests for WCSetintsAndStrings.js (code.testSet.js)
      - name: Run Tests for WCSetintsAndStrings.js (code.testSet.js)
        run: node code.testSet.js
        working-directory: ./frontend  # Adjust this if needed
